fix(ComponentDidUpdate): Prevent animation to restart
cheng-kang/react-native-lahk-marquee-label pull request #7
Opened 2018-02-22 20:08 UTC by AmilsonJunior

Animation restart only when it get finished

2018-02-22 20:18 UTC, cheng-kang commented
@AmilsonJunior Thank you very much for the PR!

Could you please explain more about what issue this PR is trying to solve?

2018-02-22 20:56 UTC, AmilsonJunior commented
@cheng-kang When componentDidUpdate is called before the animation get finished `animation.start()` is called again causing an unexpected interruption in the animation, then it starts again before it get finished.

2018-02-22 22:01 UTC, cheng-kang requested changes

2018-02-22 22:01 UTC, cheng-kang commented on index.js
> +        await this.setState({
According to [Component API - setState](https://shripadk.github.io/react/docs/component-api.html#setstate) and [source code](https://github.com/facebook/react/blob/master/packages/react/src/ReactBaseClasses.js#L53), `setState` does not return a Promise, so `await` is not doing anything here. 😉

But it does accept an optional callback.

2018-02-22 22:03 UTC, cheng-kang commented
@AmilsonJunior Also could you provide minimum steps to reproduce the issue?

Once I could reproduce the issue, I will start to test the code, and hopefully get it merged soon!

2018-02-23 13:33 UTC, AmilsonJunior commented
@cheng-kang Try to test MarqueeLabel in a View that have constantly updates on render()

2018-02-23 14:41 UTC, cheng-kang approved these changes

2018-02-23 14:42 UTC, merged

2018-02-23 14:44 UTC, cheng-kang commented
@AmilsonJunior thanks for your effort!

I will publish new version to NPM later today.